export const Gifs = {
    goLiveGif: require('../assets/gifs/goLiveGif.gif'),
    shortsGif: require('../assets/gifs/shortsGif.gif'),
    clipGif: require('../assets/gifs/clipGif.gif'),
    postGif: require('../assets/gifs/postGif.gif'),
    activityGif: require('../assets/gifs/activityGif.gif'),
    logoutGif: require('../assets/gifs/logoutGif.gif'),
    verifiedGif: require('../assets/gifs/verifiedGif.gif'),
    crownGif: require('../assets/gifs/crownGif.gif'),
    privacyGif: require('../assets/gifs/privacyGif.gif'),
    giftGif: require('../assets/gifs/giftGif.gif'),
    walletGif: require('../assets/gifs/walletGif.gif'),
    babyGif: require('../assets/gifs/babyGif.gif'),
    helpGif: require('../assets/gifs/helpGif.gif'),
    legalPolicyGif: require('../assets/gifs/legalPolicyGif.gif'),
    blockedGif: require('../assets/gifs/blockedGif.gif'),
    aboutUsGif: require('../assets/gifs/aboutUsGif.gif'),
    liveGif: require('../assets/gifs/live.gif'),
    spreadHGif: require('../assets/gifs/spreadh.gif'),
    spreadSGif: require('../assets/gifs/spreadS.gif'),
    rocketGif: require('../assets/gifs/rocketGif.gif'),
};
